# name of the branch that we are going to use taken from GitHub
trigger:
  - main

# type of the VM that is going to execute the test_ scenarios
pool: windows-latest

# steps plan
steps:
  # First step - choosing what python version we are going to use
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.x

  # Second step - Installing required packages for our automation
  - script: |
      pip install selenium pytest
      pip install -r YAML/requirements.txt
      python -m pip install pytest
      python -m pytest
    displayName: 'Install Requirements'

  # Third step - test execution
  - script: | # running the script to execute the test_scenarios full file  
      pytest -v Tests/test_scenarios.py --junitxml=junit/test-results.xml
    displayName: 'Run tests'
      
  # Fourth step - publishing HTML report of the test results
  - script: | # use pytest-html to create an HTML report from the JUnit test results
      pip install pytest-html
      pytest --junitxml=junit/test-results.xml --html=report.html
    displayName: 'Publish HTML test results report'
