# name of the branch that we are going to use taken from GitHub
trigger:
  - main

# type of the VM that is going to execute the test_ scenarios
pool: windows-latest

# steps plan
steps:
  # First step - choosing what python version we are going to use
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.x

  # Second step - Installing required packages for our automation
  - script: |
      pip install selenium pytest
      pip install -r YAML/requirements.txt
      python -m pip install pytest
      python -m pytest
    displayName: 'Second step/task Install Requirements'

  # Third step - test execution + publishing HTML report of the test results, running the script to execute the test_scenarios full file output the test results in JUnit and HTML format
  - script: |
      pip install pytest-html
      pytest -v Tests/test_scenarios.py --junitxml=junit/test-results.xml --html=report.html
    displayName: 'Third step/task - Run tests + Publish HTML test results report'

